stages:
  data_split:
      cmd: make dataSplit
      deps:
      - src/stages/data/data_split.py
      - data/raw
      params:
      - base
      - data_split
      outs:
      - data/processed
  train:
      cmd: make train
      deps:
      - src/stages/train/train.py
      - data/processed
      params:
      - base
      - train
      outs:
      - models/clf-model.joblib
  eval:
      cmd: make eval
      deps:
      - src/stages/evaluation/eval.py
      - data/processed
      - models/clf-model.joblib
      params:
      - base
      - data_split
      - train
      outs:
      - reports/feat_imp.csv:
          cache: false
      metrics:
      - reports/metrics.json:
          cache: false
      plots:
      - reports/figures/cm.png:
          cache: false